const express=require("express");
const { createTechnician, getTechnicians, getTechnicianById, updateTechnician, deleteTechnician, updateAvailability } = require("../controllers/technician.controller");
const validateTechnician = require("../validators/technician.validator");
 const router=express.Router();
 router.post("/",validateTechnician ,createTechnician);
 router.get("/",getTechnicians);
 router.get("/:id", getTechnicianById);
 router.put("/:id" ,updateTechnician);
 router.delete("/:id" ,deleteTechnician);
 router.patch("/:id/availability", updateAvailability);
 module.exports=router;